# Site settings
title: Jun Tu's Soup
email: jarvinia.tu@gmail.com
description: >
 Jun Tu's Soup, hopefully, it can help you to solve some problems in case that WOMEN get stuck when meetting some tech problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jarvnia.github.io" # the base hostname & protocol for your site
twitter_username: jtu_super
github_username:  jarvinia

# Build settings
markdown: kramdown

timezone: Australia/Sydney

defaults:
  -
    scope:
        path: "" # 一个空的字符串代表项目中所有的文件
        type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
        layout: "default"
  -
    scope:
        path: ""
        type: "photos"
    values:
        layout: "default"