# Site settings
title: Jun Tu's Soup 
author: 涂珺 Jun Tu 
email: jarvinia.tu@gmail.com
description: |
 Jun Tu's Soup, hopefully, it can help you in case of getting
 stuck with some tech problems. And I hope more and more women
 to get involved to coding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jarvinia.github.io" # the base hostname & protocol for your site
twitter_username: jtu_super
github_username:  jarvinia

# Build settings
markdown: kramdown

timezone: Australia/Sydney

paginator: 8

highlighter: pygments

defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "default"

include: .nojekyll
exclude: jekgitbuild.sh
